[package]
name = "beat-up-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.1"
# bevy_egui = "0.16"
# bevy-inspector-egui = "0.13.0"
